#!/bin/bash
## ec2-find
##
## Find all EC2 instances and return IP, instance-id, environment tag and purpose tag
##
#

set -e
set -o pipefail

QUERY='.Reservations[] | .Instances[] | '
QUERY+=' .PrivateIpAddress + "\t" + .InstanceId + "\t" + (.Tags[] | select( .Key == "Environment") | .Value) + "\t" + (.Tags[] | select( .Key == "Purpose") | .Value)'

aws ec2 describe-instances | jq -r "$QUERY"
